name: Deploy to Nekoweb

on:
  push:
    branches: [main]
  workflow_dispatch: # Allows manual trigger from Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive # Set to 'recursive' if you want checkout to handle submodules instead

      - name: Deploy to Nekoweb
        uses: alexbatesdev/deploy2nekoweb@main # Replace YOUR_USERNAME with your GitHub username
        with:
          nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
          nekoweb-domain: piinro.nekoweb.org # Replace with your Nekoweb domain
          nekoweb-username: piinro
          directory: . # Replace with your build output directory
          # Optional: uncomment to enable
          exclude-hidden: true
